#[build.environment]
#  NEXT_USE_NETLIFY_EDGE = "false"

[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"


[functions]
  included_files = [
    "!node_modules/sharp/vendor/8.12.2/darwin-*/**/*",
    "!node_modules/sharp/build/Release/sharp-darwin-*"
  ]

[[redirects]]
  from = '/_next/image/*'
  query = { q = ':quality', url = ':url', w = ':width' }
  to = '/.netlify/images?url=:url&w=:width&q=:quality'
  status = 200
  force = true

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains"
[[headers]]
    for = "/*"
    [headers.values]
        Strict-Transport-Security = '''
            max-age=63072000;
            includeSubDomains;
            preload'''
[[headers]]
  for = "/images/*"
  [headers.values]
    	cache-control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/images/uploads/*"
  [headers.values]
    	cache-control = "public, max-age=31536000, immutable"
[[headers]]
  for = "*.jpg"
  [headers.values]
    	cache-control = "public, max-age=31536000, immutable"
[[headers]]
  for = "*.css"
  [headers.values]
    	cache-control = "public, max-age=31536000, immutable"
[[headers]]
  for = "*.js"
  [headers.values]
    	cache-control = "public, max-age=31536000, immutable"
[[headers]]
  for = "*.html"
  [headers.values]
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
#[[plugins]]
#    package = "netlify-plugin-csp-generator"

#    [plugins.inputs]
#        buildDir = "dist"

#    [plugins.inputs.policies]
#        defaultSrc = "'self'"
#        styleSrc = "'self' 'unsafe-hashes'"
